namespace FilesMate.App.Localization;

public static partial class StringTable
{
    private static IReadOnlyDictionary<string, (string English, string Chinese, string Japanese)> ArchiveEntries() =>
        new Dictionary<string, (string English, string Chinese, string Japanese)>(StringComparer.Ordinal)
        {
            ["Archive_TitleCompress"] = ("Compress", "压缩", "圧縮"),
            ["Archive_TitleExtract"] = ("Extract", "解压", "展開"),
            ["Archive_CreateZip"] = ("Create archive", "创建压缩文件", "アーカイブを作成"),
            ["Archive_Unsupported"] = ("This archive format needs CompactMate or another compatible archive app.", "此压缩格式需要使用 CompactMate 或其他兼容的压缩软件。", "この形式には CompactMate または対応する圧縮ソフトが必要です。"),
            ["Archive_Progress"] = ("{0} / {1} items · {2} / {3} MB", "{0} / {1} 项 · {2} / {3} MB", "{0} / {1} 件 · {2} / {3} MB"),
            ["Archive_Cancelled"] = ("Operation cancelled.", "操作已取消。", "操作をキャンセルしました。"),
            ["Archive_Completed"] = ("Completed: {0}", "已完成：{0}", "完了：{0}"),
            ["Archive_Cancel"] = ("Cancel", "取消", "キャンセル"),
            ["Archive_ChooseDestination"] = ("Choose a destination folder", "选择目标文件夹", "保存先フォルダーを選択"),
            ["Archive_DefaultName"] = ("Archive", "压缩文件", "アーカイブ"),
            ["Archive_ExternalOnly"] = ("Requires CompactMate", "需要 CompactMate", "CompactMate が必要"),
            ["Archive_CheckingProvider"] = ("Checking CompactMate…", "正在检查 CompactMate…", "CompactMate を確認中…"),
            ["Archive_Failed"] = ("Operation failed: {0}", "操作失败：{0}", "操作に失敗しました：{0}"),
            ["Archive_InvalidSelection"] = ("Select at least one existing file or folder.", "请至少选择一个已存在的文件或文件夹。", "既存のファイルまたはフォルダーを 1 つ以上選択してください。"),
            ["Archive_NameLabel"] = ("Archive name", "压缩文件名称", "アーカイブ名"),
            ["Archive_NameInvalid"] = ("Enter a valid ZIP or 7z filename without a folder path.", "请输入有效的 ZIP 或 7z 文件名，不要包含文件夹路径。", "フォルダーのパスを含まない有効な ZIP または 7z ファイル名を入力してください。"),
            ["Archive_BuiltinHint"] = ("Create ZIP and 7z; extract ZIP, 7z, RAR and TAR archives, including supported encrypted and split archives. No other app is required.", "可创建 ZIP、7z，解压 ZIP、7z、RAR、TAR，支持常见加密包和分卷，无需安装其他软件。", "ZIP・7z の作成、ZIP・7z・RAR・TAR の展開に対応。対応形式の暗号化・分割アーカイブも他のアプリなしで展開できます。"),
            ["Archive_Cancelling"] = ("Cancelling…", "正在取消…", "キャンセル中…"),
            ["Archive_OutputLabel"] = ("Save to", "保存到", "保存先"),
            ["Archive_FolderPicker"] = ("Choose folder…", "选择文件夹…", "フォルダーを選択…"),
            ["Archive_ErrorInvalidPath"] = ("A file path is invalid or points outside the destination folder.", "文件路径无效，或指向目标文件夹以外的位置。", "ファイルのパスが無効か、保存先フォルダーの外を指しています。"),
            ["Archive_ErrorUnsafeLink"] = ("This operation includes a symbolic link or redirected folder. Choose regular files and folders.", "操作中包含符号链接或重定向文件夹，请选择普通文件和文件夹。", "シンボリックリンクまたはリダイレクトされたフォルダーが含まれています。通常のファイルやフォルダーを選択してください。"),
            ["Archive_ErrorDestinationNotEmpty"] = ("The destination folder is not empty. Choose an empty folder.", "目标文件夹不为空，请选择空文件夹。", "保存先フォルダーが空ではありません。空のフォルダーを選択してください。"),
            ["Archive_ErrorDestinationExists"] = ("The destination already exists. Choose another name or folder.", "目标已存在，请更换名称或文件夹。", "保存先は既に存在します。別の名前またはフォルダーを選択してください。"),
            ["Archive_ErrorInvalidArchive"] = ("The archive is damaged or its contents could not be verified.", "压缩文件已损坏，或内容校验失败。", "アーカイブが破損しているか、内容の検証に失敗しました。"),
            ["Archive_ErrorUnsupportedEntry"] = ("This format or compression method is not supported by the built-in engine. Use Open with archive app or the system menu.", "内置引擎不支持此格式或压缩方式，请使用“用压缩软件打开”或系统右键菜单。", "この形式または圧縮方式は標準機能に未対応です。「圧縮ソフトで開く」またはシステムメニューをご利用ください。"),
            ["Archive_ErrorMissingVolume"] = ("A volume is missing or incomplete. Place all volumes together and try again.", "分卷缺失或不完整，请将所有分卷放在同一个文件夹后重试。", "分割ファイルが不足しているか不完全です。すべて同じフォルダーに置いて再試行してください。"),
            ["Archive_ErrorPasswordRequired"] = ("A password is required, or the password or encrypted content could not be verified.", "需要密码，或密码及加密内容校验失败。", "パスワードが必要か、パスワードまたは暗号化された内容の検証に失敗しました。"),
            ["Archive_Password"] = ("Archive password", "压缩包密码", "アーカイブのパスワード"),
            ["Archive_PasswordRetry"] = ("The password did not work, or the encrypted content is damaged. Try another password.", "密码不正确，或加密内容已损坏，请尝试其他密码。", "パスワードが正しくないか、暗号化された内容が破損しています。別のパスワードをお試しください。"),
            ["Archive_Settings"] = ("Archive apps", "压缩与解压", "圧縮・展開"),
            ["Archive_Preferred"] = ("Preferred archive app", "首选压缩软件", "優先する圧縮ソフト"),
            ["Archive_PreferredHint"] = ("Choose how FileMate handles compression and extraction.", "选择 FileMate 执行压缩和解压时使用的软件。", "FileMate の圧縮・展開に使用するソフトを選択します。"),
            ["Archive_Automatic"] = ("Automatic", "自动", "自動"),
            ["Archive_BuiltIn"] = ("FileMate built-in", "FileMate 内置", "FileMate 標準機能"),
            ["Archive_360"] = ("360 Zip", "360 压缩", "360 Zip"),
            ["Archive_HaoZip"] = ("2345 HaoZip", "2345 好压", "2345 HaoZip"),
            ["Archive_SevenZipCompatible"] = ("7-Zip compatible app", "兼容 7-Zip 的软件", "7-Zip 互換ソフト"),
            ["Archive_OtherApp"] = ("Other app (open only)", "其他软件（用于打开）", "その他（開くのみ）"),
            ["Archive_AutoHint"] = ("Try CompactMate, Bandizip, 7-Zip and WinRAR in order. Use the built-in engine when none supports the operation.", "依次尝试 CompactMate、Bandizip、7-Zip、WinRAR；没有可处理此操作的软件时使用内置引擎。", "CompactMate、Bandizip、7-Zip、WinRAR の順に確認し、対応できるソフトがない場合は標準機能を使用します。"),
            ["Archive_OpenOnlyHint"] = ("Available in Open with archive app. Direct compression and extraction use the built-in engine; use the system menu for this app's own commands.", "可通过“用压缩软件打开”调用。直接压缩、解压由内置引擎完成；此软件自己的操作可从系统右键菜单使用。", "「圧縮ソフトで開く」で使用できます。直接の圧縮・展開には標準機能を使い、このソフト固有の操作はシステムメニューで使用します。"),
            ["Archive_CompatibleHint"] = ("Choose a GUI worker compatible with 7zG.exe. Console tools and unsupported operations use the built-in engine.", "请选择兼容 7zG.exe 的图形操作程序。命令行程序或不支持的操作将使用内置引擎。", "7zG.exe と互換性のある GUI プログラムを指定してください。コンソールツールや未対応の操作には標準機能を使用します。"),
            ["Archive_WinRARHint"] = ("Open archives and extract a single archive with WinRAR. Compression, batch and renamed-volume operations use the built-in engine.", "使用 WinRAR 打开或解压单个压缩包。压缩、批量处理及改名分卷由内置引擎完成。", "WinRAR でアーカイブを開き、単一アーカイブを展開します。圧縮・一括処理・改名された分割ファイルには標準機能を使用します。"),
            ["Archive_CompactMateHint"] = ("Use CompactMate's batch extraction, password library and recursive extraction when installed.", "安装后使用 CompactMate 的批量解压、密码库和内层压缩包自动解压功能。", "インストール済みの CompactMate で一括展開、パスワードライブラリ、入れ子アーカイブの自動展開を使用します。"),
            ["Archive_ExternalHint"] = ("Use this app for supported operations. Renamed volumes and unsupported operations use the built-in engine.", "支持的操作交给此软件处理；改名分卷及不支持的操作使用内置引擎。", "対応する操作にはこのソフトを使い、改名された分割ファイルや未対応の操作には標準機能を使用します。"),
            ["Archive_FallbackHint"] = ("The preferred app is unavailable or does not support this operation. Using FileMate's built-in engine.", "首选软件不可用或不支持此操作，正在使用 FileMate 内置引擎。", "優先するソフトが利用できないか、この操作に未対応のため、FileMate の標準機能を使用しています。"),
            ["Archive_SmartBuiltinHint"] = ("Built-in smart extraction chooses a tidy destination folder. Recursive extraction and password libraries require CompactMate.", "内置智能解压会自动整理目标文件夹；继续解压内层压缩包、自动尝试密码库需要 CompactMate。", "標準のスマート展開は保存先フォルダーを自動整理します。入れ子の展開とパスワードライブラリには CompactMate が必要です。"),
            ["Archive_BrowseApp"] = ("Choose program…", "指定程序…", "プログラムを指定…"),
            ["Archive_AutoDetect"] = ("Detect automatically", "恢复自动检测", "自動検出に戻す"),
            ["Archive_Detecting"] = ("Finding app…", "正在查找软件…", "ソフトを検索中…"),
            ["Archive_NotInstalled"] = ("App not found. You can specify a portable copy; otherwise the built-in engine will be used.", "未找到软件。可指定便携版程序，否则使用内置引擎。", "ソフトが見つかりません。ポータブル版を指定するか、標準機能をご利用ください。"),
            ["Archive_OpenWithApp"] = ("Open with archive app…", "用压缩软件打开…", "圧縮ソフトで開く…"),
            ["Archive_SystemOpenWith"] = ("System Open with…", "系统打开方式…", "システムの開く方法…"),
            ["Archive_ErrorTooManyEntries"] = ("This archive exceeds the built-in limit of 100,000 items.", "压缩文件超过内置功能的 100,000 项上限。", "このアーカイブは標準機能の上限である 100,000 項目を超えています。"),
            ["Archive_ErrorArchiveTooLarge"] = ("The expanded content exceeds the built-in limit of 64 GiB.", "解压后的内容超过内置功能的 64 GiB 上限。", "展開後の内容が標準機能の上限である 64 GiB を超えています。"),
            ["Archive_ErrorMetadataTooLarge"] = ("The archive's directory information exceeds the built-in limit of 64 MiB.", "压缩文件的目录信息超过内置功能的 64 MiB 上限。", "アーカイブのディレクトリ情報が標準機能の上限である 64 MiB を超えています。"),
            ["Archive_ErrorInsufficientSpace"] = ("There is not enough free space at the destination. Free some space or choose another drive.", "目标磁盘空间不足，请释放空间或选择其他磁盘。", "保存先の空き容量が不足しています。空き容量を増やすか、別のドライブを選択してください。"),
            ["Archive_ErrorSourceChanged"] = ("A source file changed during the operation. Wait for changes to finish and try again.", "来源文件在操作过程中发生了变化，请等待文件更改完成后重试。", "操作中に元のファイルが変更されました。変更が完了してから再試行してください。"),
            ["Archive_ErrorSecurityMetadataUnavailable"] = ("The file's internet-origin marker could not be read or preserved safely. Use a local drive that supports this marker, or extract with CompactMate.", "无法安全读取或保留文件的互联网来源标记。请使用支持此标记的本地磁盘，或改用 CompactMate 解压。", "ファイルのインターネット由来のマークを安全に読み取るか保持することができません。このマークに対応したローカルドライブを使用するか、CompactMate で展開してください。"),
            ["Archive_ErrorOperationFailed"] = ("The operation could not be completed. Check file permissions and available disk space, then try again.", "操作未能完成。请检查文件访问权限和磁盘可用空间，然后重试。", "操作を完了できませんでした。ファイルのアクセス権とディスクの空き容量を確認して再試行してください。"),
            ["Archive_TemporaryFilesRemain"] = ("Some temporary files could not be removed. Location: {0}", "部分临时文件未能清理，位置：{0}", "一部の一時ファイルを削除できませんでした。場所：{0}"),
        };
}
