namespace FilesMate.App.Models;

/// <summary>
/// The coordinated skin palette. Add/change colors here as a set, never in a control.
/// Component resources are generated by tools/FilesMate.ThemeGenerator; the companion
/// windows use this same palette. Functional colors (diffs, warnings, file types) are separate.
/// </summary>
public sealed record SkinPalette
{
    public required bool Dark { get; init; }
    public required uint Canvas { get; init; }
    public required uint Navigation { get; init; }
    public required uint Chrome { get; init; }
    public required uint Content { get; init; }
    public required uint Card { get; init; }
    public required uint Floating { get; init; }
    public required uint Input { get; init; }
    public required uint Text { get; init; }
    public required uint Muted { get; init; }
    public required uint Line { get; init; }
    public required uint Accent { get; init; }

    public static SkinPalette Light { get; } = new()
    {
        Dark = false, Canvas = 0xFFF8F6F0, Navigation = 0xFFF2F0E9, Chrome = 0xFFF1EFE8,
        Content = 0xFFFFFFFF, Card = 0xFFFFFFFF, Floating = 0xFFFAF9F5, Input = 0xFFF6F4EE,
        Text = 0xFF303B37, Muted = 0xFF606D66, Line = 0xFF505E55, Accent = 0xFF4F786C,
    };
    public static SkinPalette DarkSkin { get; } = new()
    {
        Dark = true, Canvas = 0xFF242424, Navigation = 0xFF202020, Chrome = 0xFF1B1B1B,
        Content = 0xFF2D2D2D, Card = 0xFF323232, Floating = 0xFF2C2C2C, Input = 0xFF323232,
        Text = 0xFFE8E8E8, Muted = 0xFFACACAC, Line = 0xFFFFFFFF, Accent = 0xFF96ABC7,
    };
    public static SkinPalette For(bool dark) => dark ? DarkSkin : Light;

    public byte SelectionAlpha => Dark ? (byte)0x30 : (byte)0x2B;
    public byte SelectionHoverAlpha => Dark ? (byte)0x3C : (byte)0x38;
    public uint Selected => Alpha(Accent, SelectionAlpha);
    public uint Hover => Alpha(Accent, 0x10);
    public uint Border => Alpha(Line, Dark ? (byte)0x1C : (byte)0x18);
    public uint Outline => Mix(Line, Floating, Dark ? .11 : .24);
    public uint ControlHover => Mix(Text, Card, .055);
    public uint ControlPressed => Mix(Text, Card, .10);

    public IReadOnlyDictionary<string, uint> CompanionColors() => new Dictionary<string, uint>
    {
        ["Surface"] = Floating, ["MenuSurface"] = Floating, ["PaletteCanvas"] = Dark ? Canvas : Floating,
        ["ResultSurface"] = Content, ["PillSurface"] = Card, ["Ink"] = Text, ["Muted"] = Muted,
        ["SelectedInk"] = Text, ["SelectedMuted"] = Muted, ["Line"] = Border, ["Outline"] = Outline,
        ["Selected"] = Selected, ["Hover"] = Hover, ["Accent"] = Accent,
    };

    public IReadOnlyDictionary<string, uint> ResourceColors()
    {
        var colors = new Dictionary<string, uint>(StringComparer.Ordinal);
        void Put(uint color, params string[] keys) { foreach (var key in keys) colors.Add(key, color); }
        var prefix = "FilesMate.Palette." + (Dark ? "Dark" : "Light") + ".";
        var foreground = AccentPalette.Foreground(Accent);
        var accentHover = foreground == 0xFF000000 ? Lift(Accent, 20) : Mix(0xFF000000, Accent, .1);
        Put(Text, prefix + "Text.PrimaryBrush", "ComboBoxDropDownGlyphForeground", "ComboBoxDropDownGlyphForegroundFocused",
            "ComboBoxDropDownGlyphForegroundPointerOver", "CalendarDatePickerForeground", "CalendarDatePickerTextForeground",
            "CalendarDatePickerTextForegroundSelected", "CalendarDatePickerTextForegroundPointerOver", "CalendarDatePickerTextForegroundPressed",
            "CalendarDatePickerHeaderForeground", "CalendarDatePickerCalendarGlyphForeground",
            "CalendarDatePickerCalendarGlyphForegroundPointerOver", "CalendarDatePickerCalendarGlyphForegroundPressed");
        Put(Muted, prefix + "Text.SecondaryBrush");
        Put(Alpha(Text, 0x66), prefix + "Text.DisabledBrush");
        Put(Canvas, "FilesMate.App.SolidBackgroundBrush", "FilesMate.CommandBar.BackgroundBrush", "FilesMate.FileArea.BackgroundBrush");
        Put(Navigation, "FilesMate.Sidebar.BackgroundBrush", "FilesMate.SettingsNav.BackgroundBrush");
        Put(Chrome, "FilesMate.Chrome.FillBrush");
        Put(Dark ? Navigation : Mix(Canvas, Navigation, .5), "FilesMate.Favorites.BackgroundBrush");
        Put(Content, "FilesMate.FileContent.BackgroundBrush");
        Put(Card, "ContentDialogTopOverlay", "LayerFillColorDefaultBrush", "FilesMate.SettingsCard.BackgroundBrush",
            "ButtonBackground", "ButtonBackgroundDisabled", prefix + "Tab.SelectedBrush", "CalendarDatePickerBackground",
            "CalendarDatePickerBackgroundFocused", "TextControlBackground", "TextControlBackgroundFocused", "TextControlBackgroundPointerOver");
        Put(Floating, "FilesMate.Update.SurfaceBrush", "FilesMate.LiquidGlass.SolidFillBrush", "FilesMate.SearchPanel.BackgroundBrush",
            "FilesMate.SettingsPanel.BackgroundBrush", "ContentDialogBackground", "ComboBoxDropDownBackground",
            "FilesMate.Menu.BackgroundBrush", "FilesMate.LiquidGlass.FillBrush", "FilesMate.InfoPane.BackgroundBrush", "FilesMate.App.BackgroundBrush");
        Put(Input, prefix + "ComboBox.BackgroundBrush");
        Put(ControlHover, "ButtonBackgroundPointerOver", "ComboBoxBackgroundPointerOver",
            "CalendarDatePickerBackgroundPointerOver");
        Put(ControlPressed, "ButtonBackgroundPressed", "ComboBoxBackgroundPressed",
            "CalendarDatePickerBackgroundPressed", "FilesMate.Glass.SurfacePressedBrush");
        // Menus float over a different surface than buttons. Cover every native item
        // type, including the persistent state while a child menu is open.
        Put(Mix(Text, Floating, .09), "FilesMate.Menu.ItemHoverBrush", "MenuFlyoutItemBackgroundPointerOver", "ToggleMenuFlyoutItemBackgroundPointerOver",
            "MenuFlyoutSubItemBackgroundPointerOver", "MenuFlyoutSubItemBackgroundSubMenuOpened");
        Put(Mix(Text, Floating, .15), "FilesMate.Menu.ItemPressedBrush", "MenuFlyoutItemBackgroundPressed", "ToggleMenuFlyoutItemBackgroundPressed",
            "MenuFlyoutSubItemBackgroundPressed");
        Put(Mix(Line, Floating, .24), "MenuFlyoutSeparatorBackground");
        Put(Muted, "RadioButtonOuterEllipseStroke");
        Put(Text, "RadioButtonOuterEllipseStrokePointerOver", "RadioButtonOuterEllipseStrokePressed");
        Put(Card, "RadioButtonOuterEllipseFill");
        Put(Mix(Text, Floating, .09), "RadioButtonOuterEllipseFillPointerOver");
        Put(Mix(Text, Floating, .15), "RadioButtonOuterEllipseFillPressed");
        Put(Mix(Card, Canvas, .5), "TextControlBackgroundDisabled", "ComboBoxBackgroundDisabled");
        Put(Border, prefix + "AddressBar.BorderBrush", "FilesMate.Glass.BorderBrush", "FilesMate.Divider.Brush",
            "ContentDialogBorderBrush", "ContentDialogSeparatorBorderBrush", "DividerStrokeColorDefaultBrush",
            "ButtonBorderBrush", "ButtonBorderBrushPointerOver", "ButtonBorderBrushPressed", "FilesMate.Tab.BorderBrush");
        Put(Alpha(Line, Dark ? (byte)0x3A : (byte)0x30), prefix + "ComboBox.BorderBrush", "FilesMate.Glass.BorderStrongBrush",
            "TextControlBorderBrush", "TextControlBorderBrushPointerOver");
        Put(Alpha(Line, Dark ? (byte)0x14 : (byte)0x20), "FilesMate.FileContent.BorderBrush", "FilesMate.Card.BorderBrush");
        Put(Outline, "FilesMate.Floating.OutlineBrush", "CalendarDatePickerBorderBrush", "CalendarDatePickerBorderBrushPointerOver",
            "CalendarDatePickerBorderBrushPressed");
        Put(Mix(Line, Navigation, .09), "FilesMate.Shell.SeparatorBrush", "FilesMate.Sidebar.SeparatorBrush");
        Put(Muted, "CheckBoxCheckBackgroundStrokeUnchecked", "CheckBoxCheckBackgroundStrokeUncheckedPointerOver",
            "CheckBoxCheckBackgroundStrokeUncheckedPressed", "ScrollBarThumbFill", "ScrollBarThumbBackground",
            "ScrollBarPanningThumbBackground", "ScrollBarButtonArrowForeground", "ScrollBarThumbBackgroundColor", "ScrollBarPanningThumbBackgroundColor");
        Put(Text, "ScrollBarThumbFillPointerOver", "ScrollBarButtonArrowForegroundPointerOver", "ScrollBarThumbFillPressed",
            "ScrollBarButtonArrowForegroundPressed");
        Put(Mix(Muted, Canvas, .4), "ScrollBarThumbFillDisabled", "ScrollBarPanningThumbBackgroundDisabled", "ScrollBarButtonArrowForegroundDisabled");
        Put(Mix(Line, Canvas, .07), "ScrollBarTrackFill", "ScrollBarTrackFillPointerOver", "ScrollBarTrackFillDisabled",
            "ScrollBarTrackStroke", "ScrollBarTrackStrokePointerOver", "ScrollBarTrackStrokeDisabled");
        Put(Accent, "FilesMate.Glass.AccentBrush", "FilesMate.Selection.AccentBrush", "ToggleSwitchFillOn", "ToggleSwitchStrokeOn",
            "AccentButtonBackground", "ToggleButtonBackgroundChecked", "RadioButtonOuterEllipseCheckedStroke", "RadioButtonOuterEllipseCheckedFill");
        Put(accentHover, "FilesMate.Glass.AccentHoverBrush", "ToggleSwitchFillOnPointerOver", "ToggleSwitchFillOnPressed",
            "ToggleSwitchStrokeOnPointerOver", "ToggleSwitchStrokeOnPressed", "AccentButtonBackgroundPointerOver", "AccentButtonBackgroundPressed",
            "ToggleButtonBackgroundCheckedPointerOver", "ToggleButtonBackgroundCheckedPressed",
            "RadioButtonOuterEllipseCheckedStrokePointerOver", "RadioButtonOuterEllipseCheckedStrokePressed",
            "RadioButtonOuterEllipseCheckedFillPointerOver", "RadioButtonOuterEllipseCheckedFillPressed");
        Put(Selected, "FilesMate.Glass.AccentSoftBrush", "FilesMate.Compare.SourceFillBrush", "FilesMate.Item.SelectedBrush");
        Put(Alpha(Accent, SelectionHoverAlpha), "FilesMate.Item.SelectedHoverBrush", "FilesMate.Item.DropTargetBrush", "ComboBoxItemBackgroundSelectedPointerOver");
        Put(Hover, "FilesMate.Item.HoverBrush", "FilesMate.IconFrame.FillBrush", "ComboBoxItemBackgroundPointerOver", "FilesMate.Home.IconBackgroundBrush");
        Put(Selected, "ComboBoxItemBackgroundPressed");
        Put(foreground, "FilesMate.Glass.AccentForegroundBrush", "TextOnAccentFillColorPrimaryBrush", "AccentButtonForeground",
            "AccentButtonForegroundPointerOver", "AccentButtonForegroundPressed", "ToggleButtonForegroundChecked",
            "ToggleButtonForegroundCheckedPointerOver", "ToggleButtonForegroundCheckedPressed",
            "RadioButtonCheckGlyphFill", "RadioButtonCheckGlyphFillPointerOver", "RadioButtonCheckGlyphFillPressed");
        Put(Alpha(Text, 0x08), "FilesMate.Item.StripeBrush");
        Put(Alpha(Text, 0x0A), "FilesMate.FileArea.InactiveBackgroundBrush");
        Put(Alpha(Text, 0x01), "FilesMate.TextControl.CaretHostBrush");
        Put(Alpha(Card, 0xF0), "FilesMate.AddressBar.BackgroundBrush");
        Put(Alpha(Dark ? Text : Card, Dark ? (byte)0x0F : (byte)0xB8), "FilesMate.Glass.SurfaceBrush");
        Put(Alpha(Dark ? Text : Card, Dark ? (byte)0x19 : (byte)0xDF), "FilesMate.Glass.SurfaceHoverBrush");
        Put(Alpha(Dark ? Text : Card, Dark ? (byte)0x1A : (byte)0x78), "FilesMate.Glass.CardBrush");
        Put(Alpha(Dark ? Text : Card, Dark ? (byte)0x17 : (byte)0x99), "FilesMate.Glass.HighlightBrush");
        Put(Alpha(Dark ? Text : Card, Dark ? (byte)0x10 : (byte)0x59), "FilesMate.Glass.SheenBrush", "FilesMate.LiquidGlass.InnerHighlightBrush");
        Put(Alpha(Dark ? Text : Card, Dark ? (byte)0x20 : (byte)0x62), "FilesMate.IconFrame.HighlightBrush");
        Put(Border, "FilesMate.IconFrame.BorderBrush", "FilesMate.LiquidGlass.BorderBrush");
        Put(Alpha(Card, 0), prefix + "Tab.BackgroundBrush");
        Put(Alpha(0xFF000000, Dark ? (byte)0x26 : (byte)0x1A), "FilesMate.SettingsOverlay.ScrimBrush");
        Put(Alpha(0xFF000000, 0x24), "FilesMate.LiquidGlass.ShadowBrush");
        Put(Light.Canvas, "FilesMate.ThemePreview.LightFill");
        Put(DarkSkin.Canvas, "FilesMate.ThemePreview.DarkFill");
        return colors;
    }

    public static uint Alpha(uint color, byte alpha) => (color & 0xFFFFFF) | ((uint)alpha << 24);
    public static uint Mix(uint color, uint background, double amount)
    {
        uint Channel(int shift) => (uint)Math.Round(((color >> shift) & 255) * amount + ((background >> shift) & 255) * (1 - amount));
        return 0xFF000000 | Channel(16) << 16 | Channel(8) << 8 | Channel(0);
    }
    private static uint Lift(uint color, byte amount)
    {
        uint Channel(int shift) => Math.Min(255, ((color >> shift) & 255) + amount);
        return 0xFF000000 | Channel(16) << 16 | Channel(8) << 8 | Channel(0);
    }
}
